# Generated by Django 3.0 on 2021-12-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211216_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(blank=True, verbose_name='Fecha de Publicacion'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
