# Generated by Django 3.0 on 2021-12-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211218_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicacion'),
        ),
    ]
