# Generated by Django 3.0 on 2021-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211220_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slug'),
        ),
    ]
